# Generated by Django 5.0.3 on 2024-07-03 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='Book ID')),
                ('citation', models.CharField(max_length=80, null=True)),
            ],
            options={
                'ordering': ['bid'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('pid', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='Party ID')),
                ('year', models.SmallIntegerField(null=True)),
                ('month', models.SmallIntegerField(null=True)),
                ('day', models.SmallIntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'parties',
                'ordering': ['year', 'month', 'day'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('qid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Wikidata QID')),
                ('name', models.CharField(max_length=200)),
                ('birth', models.DateField(null=True)),
                ('death', models.DateField(null=True)),
            ],
            options={
                'ordering': ['name', 'qid'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('sid', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='Source ID')),
                ('quote', models.TextField()),
                ('pages', models.CharField(max_length=80, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.book')),
            ],
            options={
                'ordering': ['sid'],
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presumed', models.BooleanField(default=False)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.party')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.person')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.source')),
            ],
            options={
                'ordering': ['party', 'guest'],
                'unique_together': {('party', 'guest', 'source')},
            },
        ),
    ]
