# Generated by Django 5.0.3 on 2024-04-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='death',
            field=models.DateField(null=True),
        ),
    ]
