# Generated by Django 5.0.3 on 2024-04-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_alter_person_birth_alter_person_death'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('sid', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=80, null=True)),
                ('quote', models.CharField(max_length=1000)),
                ('pages', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
