# Generated by Django 5.0.3 on 2024-04-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='quote',
            field=models.TextField(),
        ),
    ]
