# Generated by Django 5.0.3 on 2024-04-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_alter_source_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='sid',
            field=models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='Source ID'),
        ),
    ]
