# Generated by Django 5.0.3 on 2024-04-06 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0008_alter_party_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.person')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.party')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.source')),
            ],
            options={
                'unique_together': {('party', 'name', 'source')},
            },
        ),
    ]
