# Generated by Django 5.0.3 on 2024-04-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0009_guest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['party', 'name']},
        ),
    ]
