# Generated by Django 5.0.3 on 2024-04-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0010_alter_guest_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guest',
            new_name='Mention',
        ),
    ]
