# Generated by Django 5.0.3 on 2024-04-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0012_alter_mention_options_rename_name_mention_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='qid',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Wikidata QID'),
        ),
    ]
