# Generated by Django 5.0.3 on 2024-04-15 12:08

from django.db import migrations


def add_Q_prefix(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Person = apps.get_model("parties", "Person")
    Mention = apps.get_model("parties", "Mention")
    for person in Person.objects.all():
        oldqid = person.qid
        person.qid = f"Q{oldqid}"
        person.save()

        mentions = Mention.objects.filter(guest=oldqid)
        for m in mentions:
            m.guest = person
            m.save()

    for person in Person.objects.all():
        if not person.qid.startswith('Q'):
            person.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0013_alter_person_qid'),
    ]

    operations = [
        migrations.RunPython(add_Q_prefix),
    ]
