# Generated by Django 5.0.3 on 2024-07-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0014_datamigration_for_person_qid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='presumed',
        ),
        migrations.AddField(
            model_name='mention',
            name='presumed',
            field=models.BooleanField(default=False),
        ),
    ]
