# Generated by Django 5.0.3 on 2024-07-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0015_remove_person_presumed_mention_presumed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='year',
            field=models.SmallIntegerField(null=True),
        ),
    ]
