# Generated by Django 5.0.3 on 2024-07-02 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='aliases',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birthname',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birthplace',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='deathcause',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='occupation',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='spouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parties.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
