# Generated by Django 5.0.3 on 2024-07-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0017_person_aliases_person_birthname_person_birthplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='death',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
